FROM shellmanager/shellmanager

COPY . /src

# TODO: ease exfil of artifacts and config
RUN shell_manager install /src \
    && shell_manager deploy all

# TODO: default need to make explicit in standalone
EXPOSE 24399
CMD ["xinetd", "-dontfork"]
